### ISSUE TITLE
Version 2.23.0 Fails to Build

### ISSUE THREAD

**Issue by blimmer** [DataDog/datadog-lambda-layer-js#73]
## Expected Behavior

I expected 2.23.0 to build with Parcel just like 2.22.0 did.

## Actual Behavior

I get a build failure when I try to build with 2.23.0.

```
🚨  /private/tmp/test-datadog/node_modules/cls-hooked/context.js:7:28: Cannot resolve dependency 'async_hooks'
   5 | const assert = require('assert');
   6 | const wrapEmitter = require('emitter-listener');
>  7 | const async_hooks = require('async_hooks');
     |                            ^
   8 |
   9 | const CONTEXTS_SYMBOL = 'cls@contexts';
  10 | const ERROR_SYMBOL = 'error@context';
```

## Steps to Reproduce the Problem

Follow the steps in this sample repo: https://github.com/blimmer/datadog-lambda-layer-js-issue (see README)

## Specifications

  - Datadog Lambda Layer version: 2.23.0
  - Node version: 12.16.3 (12 LTS)
  
## Stacktrace
  
  ```
🚨  /private/tmp/test-datadog/node_modules/cls-hooked/context.js:7:28: Cannot resolve dependency 'async_hooks'
   5 | const assert = require('assert');
   6 | const wrapEmitter = require('emitter-listener');
>  7 | const async_hooks = require('async_hooks');
     |                            ^
   8 |
   9 | const CONTEXTS_SYMBOL = 'cls@contexts';
  10 | const ERROR_SYMBOL = 'error@context';
  ```

**Comment by agocs** [comment]
Hi @blimmer, thanks for filing this issue. I replicated it on my machine. At a guess, looks like the's some bad interaction between Parcel and cls-hooked (which aws-xray-sdk-core added as a requirement in 3.0.0). This appears to be a known issue in Parcel 1.x https://github.com/parcel-bundler/parcel/issues/3151

I think the low-effort workaround for now might be to use webpack instead of parcel, or to try parcel@2.0.0-alpha.3.2 . @DarcyRaynerDD , can you think of anything else off the top of your head?

**Comment by blimmer** [comment]
Unfortunately, I'm kind of stuck with Parcel ^1 because I'm using the [aws-cdk's NodejsFunction construct](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html), which only builds build Parcel ^1.

It looks like someone else is in the same boat: https://github.com/parcel-bundler/parcel/issues/3151#issuecomment-618453216

But fair enough, it does seem like it's not an issue with this package. Thanks for the link over to parcel.

**Comment by agocs** [comment]
Yep! Sorry this isn't an easy fix

**Comment by DarcyRaynerDD** [comment]
Hmm, @agocs  from our end we could potentially make aws-xray-sdk-core an optional dependency. Otherwise, is it possible to define externals with Parcel? I haven't used it, but I believe it's built on top of webpack. You could mark our library as external and attach the layer to your lambda, instead of bundling it.

**Comment by blimmer** [comment]
Huh, that's an interesting idea. I had thought about using the layer originally, but I wanted to be able to run / unit test locally, so I opted for the NPM package. I opened https://github.com/aws/aws-cdk/issues/7779 with CDK to see if they can support newer versions of Parcel to work around this. Since the dependency that's ultimately causing the problem is another AWS package, I think there's merit to figuring out how to fix the problem on their end.
